In [149]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [150]:
import numpy as np
import pandas as pd
import seaborn as sns   
from sklearn.model_selection import train_test_split
import tensorflow as tfs
from tensorflow import keras

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df = pd.read_csv(url, names=columns)

In [151]:
#컬럼명 확인
df

     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [152]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')

In [153]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

# 컬럼을 숫자로 변환
df.loc[:, 'buying'] = label_encoder.fit_transform(df['buying'])
df.loc[:, 'maint'] = label_encoder.fit_transform(df['maint'])
df.loc[:, 'doors'] = label_encoder.fit_transform(df['doors'])
df.loc[:, 'persons'] = label_encoder.fit_transform(df['persons'])
df.loc[:, 'lug_boot'] = label_encoder.fit_transform(df['lug_boot'])
df.loc[:, 'safety'] = label_encoder.fit_transform(df['safety'])
df.loc[:, 'class'] = label_encoder.fit_transform(df['class'])

In [154]:
df

     buying maint doors persons lug_boot safety class
0         3     3     0       0        2      1     2
1         3     3     0       0        2      2     2
2         3     3     0       0        2      0     2
3         3     3     0       0        1      1     2
4         3     3     0       0        1      2     2
...     ...   ...   ...     ...      ...    ...   ...
1723      1     1     3       2        1      2     1
1724      1     1     3       2        1      0     3
1725      1     1     3       2        0      1     2
1726      1     1     3       2        0      2     1
1727      1     1     3       2        0      0     3

[1728 rows x 7 columns]

In [155]:
df['buying'] = df['buying'].astype('float64')
df['maint'] = df['maint'].astype('float64')
df['doors'] = df['doors'].astype('float64')
df['persons'] = df['persons'].astype('float64')
df['lug_boot'] = df['lug_boot'].astype('float64')
df['safety'] = df['safety'].astype('float64')
df['class'] = df['class'].astype('float64')

In [156]:
X = df.drop('class',axis=1)
X.head()

   buying  maint  doors  persons  lug_boot  safety
0     3.0    3.0    0.0      0.0       2.0     1.0
1     3.0    3.0    0.0      0.0       2.0     2.0
2     3.0    3.0    0.0      0.0       2.0     0.0
3     3.0    3.0    0.0      0.0       1.0     1.0
4     3.0    3.0    0.0      0.0       1.0     2.0

In [157]:
y = df['class']
y.head()

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: class, dtype: float64

In [158]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [159]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [160]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))

--- SVM Classifier ---
0.9212962962962963
[[ 82   1  15   1]
 [  7  11   0   3]
 [  2   0 294   0]
 [  5   0   0  11]]

In [161]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0, solver='lbfgs',max_iter=30000)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

--- Logistic Regression Classifier ---
0.6550925925925926
[[ 11   0  84   4]
 [  1   0  20   0]
 [ 24   0 269   3]
 [  4   0   9   3]]

In [162]:
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))

--- Neural Network Classifier ---
0.9351851851851852
[[ 92   0   6   1]
 [  7  13   0   1]
 [  8   1 287   0]
 [  4   0   0  12]]

In [163]:

# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.9768518518518519
[[ 92   4   3   0]
 [  0  21   0   0]
 [  2   0 294   0]
 [  1   0   0  15]]

In [164]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Radom Forest ---

0.9745370370370371
[[ 95   3   1   0]
 [  2  19   0   0]
 [  3   0 293   0]
 [  2   0   0  14]]